### PR TITLE
Fix Windows compilation / update microseconds extraction

### PR DESCRIPTION
**Pull request by StiventoUser**
Hi matthijs,
I've made some changes to build the library on both Windows and Linux.
Here is current CI status:
gcc - ok, clang fails in the date library with string_view: https://travis-ci.org/StiventoUser/sqlpp11-connector-postgresql/builds/349046338 
VS - ok: https://ci.appveyor.com/project/StiventoUser/sqlpp11-connector-postgresql/build/1.0.36
Also, there was a problem with microseconds extraction which hopefully is fixed now (I've run tests 50 times).
I'm not using Linux often, so could you review the branch to not break build/install process?

### CODE REVIEW

**Comment by matthijs** [comment]
Thank you for the pr. Too bad that I also started a bit of work on that side. Could you try to rebase it against the develop branch?

I'll wait for you to finish 👍

**Comment by StiventoUser** [comment]
I've rebased it. Looks like the build is still fine.

**Comment by matthijs** [comment]
Thank you very much, I will look into this in the evening.

**Comment by StiventoUser** [comment]
Cool. Will wait for that.

**Comment by matthijs** [comment]
I'm sorry, I had a maintenance issue this evening that took way more time then expected. I'll try to look into it tomorrow.

**Comment by matthijs** [comment]
Thanks for your pull request, looking good and merged.

**Comment by StiventoUser** [comment]
Cool, thanks :)

**Pull request merged**
