### PR TITLE
Fix: uncomment timezone shifting code in bind_result ; explicitely 'SET TIME ZONE' in tests to pass CI

### PR DESCRIPTION
**Pull request by gagbo**
This hopefully will fix travis CI.

Clang-format gave spurrious changes, I kept them since the project has a
clang-format file

### CODE REVIEW

**Comment by gagbo** [comment]
I've seen the problem now : timezone is not parsed correctly in some cases.

In this [Travis build](https://travis-ci.org/matthijs/sqlpp11-connector-postgresql/builds/564644961#L992) the timezone is `+00` but parsed as `+3:00` (maybe because of the last char in the ms)

**Comment by gagbo** [comment]
Of course this fails.

It seems that the error comes from VS2017 using a localtime as `system_clock` instead of UTC.

Therefore :
- In the DateTime and DateTest tests, `now` is not UTC
- When [setting the table](https://ci.appveyor.com/project/matthijs/sqlpp11-connector-postgresql/builds/26295692/job/n0v6ngo67lbjm5jl#L1649), Postgres understands somehow that the naive timestamp given should use the localtime
- Uncommenting the timezone shifting makes the `.value()` call convert the value to UTC
- The `require_equal` compares the correct UTC time (from the postgres table), to a bad `now` value (which is the localtime, but without tz information)

No idea what behaviour is "wanted" here. @matthijs any idea ?

**Comment by matthijs** [comment]
@gagbo Thank you for your thorough research on this.

I'll expected the call to std::chrono::system_clock::now() to be UTC. But this seems not the case for VS2017 and it is not enforced by the C++ standard either. In the upcoming standard (c++20) this is enforced to be UTC (see: https://en.cppreference.com/w/cpp/chrono/system_clock)

In my opinion now() should be UTC. Do you know a way to get the UTC instead of the localtime with VS2017? I do not have access to VS2017 to investigate...

**Comment by gagbo** [comment]
Me neither :) I'll try to look for more information on compile flags maybe

**Comment by gagbo** [comment]
Theoretically, VS2017 also returns an UTC time point with `system_clock::now()` [Link to docs.microsoft](https://docs.microsoft.com/en-us/cpp/standard-library/system-clock-structure?view=vs-2017#remarks)

So either there's a bug in the appveyor build, or there's something we might do wrong when getting `now()`, or the docs are wrong

**Comment by gagbo** [comment]
Looking at [9.6 docs](https://www.postgresql.org/docs/9.6/datatype-datetime.html#DATATYPE-DATETIME-INPUT) it looks like some settings in [postgresql.conf](https://www.postgresql.org/docs/9.6/runtime-config-client.html#GUC-TIMEZONE) can ensure that 'naive' timestamps without timezones are interpreted as UTC.

Other solutions seem to include
> The TimeZone configuration parameter can be set in the file postgresql.conf, or in any of the other standard ways described in Chapter 19. There are also some special ways to set it:
    The SQL command SET TIME ZONE sets the time zone for the session. This is an alternative spelling of SET TIMEZONE TO with a more SQL-spec-compatible syntax.
    The PGTZ environment variable is used by libpq clients to send a SET TIME ZONE command to the server upon connection.

**Comment by gagbo** [comment]
Looks like the issue was the time zone postgres assumed when given naive timestamps for a `TIMESTAMP WITH TIMEZONE` column.

This is fixed by explicitely calling `SET TIME ZONE 'UTC'` before the tests.

**Comment by matthijs** [comment]
Thank you for your effort to fix the issues (closes: #46, #57, #66)

**Pull request merged**
